[package]
name = "gh-profile"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["sql"]

[dependencies]
sql_queries = { path = "sql" }
tokio-postgres = "0.7.16"
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros"] }
itertools = "0.14.0"
dotenvy = "0.15.7"
